---

- hosts: all
  vars_files:
    - vars/vagrant.yml
    - vars/app.yml
  roles:
    ## Server provisioning roles:
    - { role: linux-prereqs, tags: ['linux-prereqs'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: rbenv, tags: ['rbenv'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: oh-my-zsh, tags: ['oh-my-zsh'] }
    - { role: prepare_app, tags: ['prepare_app'] }
    - { role: git-config, tags: ['git-config'] }
